name: Deploy Infra 🔨

on:
  push:
    branches:
      - main
    paths:
      - infra/*

env:
  AWS_REGION: us-east-1

jobs:
  check-changes:
    name: Check for Template Changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      templates: ${{ steps.check.outputs.templates }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Check changed templates 
        id: check
        run: | 
          # Get the names of changed templates between the current and the last commit
          changed_files=$(git diff --name-only HEAD~1 HEAD)
          infra_filenames=$(echo "$changed_files" | grep '^infra/[^/]*\.yml$' | awk -F'/' '{print $NF}')
          json_output=$(echo "$infra_filenames" | jq -c -R -s 'split("\n") | map(select(. != ""))')
          echo "templates=$json_output" >> "$GITHUB_OUTPUT"

  create-change-sets:
    name: Create Change Set
    needs: check-changes
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        template: ${{ fromJson(needs.check-changes.outputs.templates) }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GH_OIDC_ROLE_ARN }}
          role-session-name: easytransfer 
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Process file
        run: |
          STACK=$(basename "${{ matrix.template }}" .yml)
  
          echo "=== Checking if stack exists ==="
          if aws cloudformation describe-stacks --stack-name "$STACK" --region "${{ env.AWS_REGION }}" >/dev/null 2>&1; then
            echo "Stack exists. Creating changeset and storing in a variable."
            CHANGESET_ID=$(aws cloudformation create-change-set \
              --change-set-name "${STACK}-$(date +%Y%m%d%H%M%S)" \
              --stack-name $STACK \
              --template-body file://infra/${{ matrix.template }} \
              --region "${{ env.AWS_REGION }}" \
              --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
              --on-stack-failure ROLLBACK \
              --query 'Id' \
              --output text)
          else
            echo "Stack does not exist. Creating stack $STACK."
            aws cloudformation create-stack \
              --stack-name "$STACK" \
              --template-body file://infra/${{ matrix.template }} \
              --region "${{ env.AWS_REGION }}" \
              --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
          fi

          if [ -z "$CHANGESET_ID" ]; then
            echo "CHANGESET_ID is empty or not set. Skipping next Job."
            echo "SKIP=true" >> $GITHUB_ENV
          fi

          echo "=== Forwarding ChangeSet ID to Next Step ==="
          echo "CHANGESET_ID=$CHANGESET_ID" >> $GITHUB_ENV
          echo "STACK_NAME=$STACK" >> $GITHUB_ENV

      - name: Matrix Output
        uses: beacon-biosignals/matrix-output@v1
        id: matrix-output
        with:
          yaml: |
            changeset-id: ${{ env.CHANGESET_ID }}
            stack-name: ${{ env.STACK_NAME }}
            skip: ${{ env.SKIP }}

    outputs:
      json: ${{ steps.matrix-output.outputs.json }}
  
  execute-change-sets:
    name: Execute Change Set
    needs: create-change-sets
    runs-on: ubuntu-latest
    environment: infra-prd
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        json: ${{ fromJson(needs.create-change-sets.outputs.json) }}
    steps:
      - name: Exit Early If Nothing to Do
        run: |
          SKIP=${{ matrix.json.skip }}
          if [ $SKIP == "true" ]; then
            echo "=== Nothing to do. Exiting job ==="
            exit 0
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GH_OIDC_ROLE_ARN }}
          role-session-name: easytransfer 
          aws-region: ${{ env.AWS_REGION }}

      - name: Execute Changeset
        run: |
          CHANGESET_ID="${{ matrix.json.changeset-id }}"
          STACK_NAME="${{ matrix.json.stack-name }}"
          echo "=== Executing Changeset ==="
          echo "=== Stack: $STACK_NAME ==="

          aws cloudformation execute-change-set \
            --change-set-name $CHANGESET_ID 

          echo "=== Executed Changeset ==="
